version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/certificate.crt:/etc/nginx/certs/certificate.crt
      - ./cert/private.key:/etc/nginx/certs/private.key