version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/certificate.crt:/etc/nginx/certs/certificate.crt
      - ./cert/private.key:/etc/nginx/certs/private.key
    environment:
      PRIVATE_IP_BACK: ${PRIVATE_IP_BACK:-http://backend}
      PORT_BACK: ${PORT_BACK:-4000}
      PRIVATE_IP_FRONT: ${PRIVATE_IP_FRONT:-http://frontend}
      PORT_FRONT: ${PORT_FRONT:-3000}
